apiVersion: v1
kind: Service
metadata:
  name: <preffered-name>-service
  namespace: <preffered-name>-ns
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"<preffered-name>-backend"}}'
spec:
  selector:
    app: <preffered-name>-deployment
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort